const constants = {
  CHANGE_PAGE: 'CHANGE_PAGE',
  CHANGE_USER: 'CHANGE_USER',
  CHANGE_OBIEWS: 'CHANGE_OBIEWS',
  CREATE_NEW_OBIEW: 'CREATE_NEW_OBIEW',
  CREATE_NEW_COMMENT: 'CREATE_NEW_COMMENT',
  CREATE_NEW_LIKE: 'CREATE_NEW_LIKES',
  DELETE_LIKE: 'DELETE_LIKE',
}

export default constants;